### ISSUE TITLE
Screenshots for Available Mods

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/mtmods4android#25]

**Comment by Wilker-a** [comment]
the screenshots in the mods list seems squashed. can those images be made so they appear in full scale instead of a circle, or at least cropped instead of resized, or have a logo whenever available?
![a cropped screenshot of the mods list, highlighting the icons consisting of screenshots of their respective mods. the screenshots are resized to fit the 1:1 scale of the circle shape, making them appear squashed.](https://user-images.githubusercontent.com/10854855/64070658-08d82d80-cc3c-11e9-8de5-913b04a0a1c7.png)

thank you for reading \^w\^
